version: '3'

services:
    db:
        image: mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    app:
        build: .docker/go
        security_opt:
            - seccomp:unconfined
        volumes:
            - ./:/go/src/github.com/jelito/money-maker
        working_dir: /go/src/github.com/jelito/money-maker
        tty: true
        #command: go run main.go --input=./data/input.csv --csv-output=./data/output.csv --std-output=true
